version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: "on-failure"
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    image: mali/service-flow-config
    restart: "on-failure"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    image: mali/service-flow-registry
    restart: "on-failure"
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    image: mali/service-flow-gateway
    restart: "on-failure"
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    image: mali/service-flow-monitoring
    restart: "on-failure"
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  fizz-buzz-service:
    image: mali/service-flow-fizz-buzz-service
    restart: "on-failure"
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"